name: counter
description: A web server for flutter counter app
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.20.0 <3.0.0'

dependencies:
  aqueduct: ^4.0.0-b1

dev_dependencies:
  test: ^1.3.3
  aqueduct_test: ^2.0.0-b1

dependency_overrides:
  postgres: 2.2.0
